/**
 * Compile-time feature flags.
 *
 * PROBLEM_SOURCE controls how the extension gets problem + acceptance data:
 *
 *   'github'   – Mode A (default):
 *       Problems from GitHub (no auth, generated by GitHub Actions).
 *       Acceptance statuses from LeetCode via batched `problemsetQuestionList`
 *       queries (authenticated, stored as a separate status overlay).
 *
 *   'leetcode' – Mode B:
 *       Problems + statuses fetched directly from LeetCode in one pass
 *       (batched, authenticated). GitHub is not used.
 *
 * Both modes keep the `recentAcSubmissionList` incremental sync as a fast
 * supplement for very recent solves that haven't appeared in the full
 * status fetch yet.
 */
export const PROBLEM_SOURCE: 'github' | 'leetcode' = 'leetcode';
